require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  DisabledByDefault: false
  TargetRubyVersion: 2.7
  Exclude:
      - 'vendor/**/*'
      - 'gemfiles/vendor/**/*'

#################### Lint ################################

Layout/LineLength:
  Description: 'Limit lines to 120 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Exclude:
    - 'spec/**/*'
    - 'lib/capybara/spec/**/*'
  AllowedPatterns:
    - '\s+# _?rubocop'
    - '^\s*#'
    - '^\s*(raise|warn|Capybara::Helpers.warn) '
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/capybara/spec/**/*'
    - 'capybara.gemspec'
  AllowedMethods:
    - Capybara.add_selector
    - Capybara::Selector::FilterSet.add

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
  CountComments: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/capybara/driver/base.rb'
    - 'lib/capybara/driver/node.rb'

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/EmptyBlock:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*.rb'

Naming/PredicateName:
  Exclude:
    - '**/*/*matchers.rb'

Naming/MethodParameterName:
  AllowedNames:
    - 'el'
    - 'id'
    - 'c'
    - 'x'
    - 'y'
    - 'on'

Style/ParallelAssignment:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/Alias:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'

Style/SpecialGlobalVars:
  Exclude:
    - 'capybara.gemspec'

Style/IfUnlessModifier:
  Exclude:
    - 'spec/**/*'

Style/AccessorGrouping:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationWidth:
  AllowedPatterns: ['^\s*module']

Security/YAMLLoad:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'

Performance/MethodObjectAsBlock:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/InstanceVariable:
  AssignmentOnly: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/PredicateMatcher:
  Exclude:
    - 'spec/basic_node_spec.rb'

RSpec/Capybara/FeatureMethods:
  Enabled: false
