require:
  - rubocop-rspec

AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.3.0
  Exclude:
      - 'capybara.gemspec'

#################### Lint ################################

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/capybara/spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
  CountComments: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/capybara/driver/base.rb'
    - 'lib/capybara/driver/node.rb'

Lint/HandleExceptions:
  Exclude:
    - 'spec/**/*'

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Naming/PredicateName:
  Exclude:
    - '**/*/*matchers.rb'

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'el'
    - 'id'
    - 'c'
    - 'x'
    - 'y'
    - 'on'

Style/RescueStandardError:
    Exclude:
      - 'spec/**/*'
      - 'lib/capybara/spec/**/*'

Style/ParallelAssignment:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Alias:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'

Style/MultilineIfModifier:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentArray:
  EnforcedStyle: consistent

Security/YAMLLoad:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'

RSpec/ExampleWording:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false
