require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  DisabledByDefault: false
  TargetRubyVersion: 2.5
  Exclude:
      - 'vendor/**/*'
      - 'gemfiles/vendor/**/*'

#################### Lint ################################

Layout/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Exclude:
    - 'spec/**/*'
    - 'lib/capybara/spec/**/*'
  IgnoredPatterns:
    - '\s+# _?rubocop'
    - '^\s*#'
    - '^\s*(raise|warn|Capybara::Helpers.warn) '
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/capybara/spec/**/*'
    - 'capybara.gemspec'
  ExcludedMethods:
    - Capybara.add_selector
    - Capybara::Selector::FilterSet.add

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
  CountComments: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/capybara/driver/base.rb'
    - 'lib/capybara/driver/node.rb'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Naming/PredicateName:
  Exclude:
    - '**/*/*matchers.rb'

Naming/MethodParameterName:
  AllowedNames:
    - 'el'
    - 'id'
    - 'c'
    - 'x'
    - 'y'
    - 'on'

Style/ParallelAssignment:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/Alias:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'

Style/SpecialGlobalVars:
  Exclude:
    - 'capybara.gemspec'

Style/IfUnlessModifier:
  Exclude:
    - 'spec/**/*'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/AccessorGrouping:
  Enabled: false
  
Style/BisectedAttrAccessor:
  Enabled: false
  
Style/RedundantAssignment:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true
  
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationWidth:
  IgnoredPatterns: ['^\s*module']

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Security/YAMLLoad:
  Exclude:
    - 'lib/capybara/spec/**/*'
    - 'spec/**/*'

Performance/AncestorsInclude:
  Enabled: true
  
Performance/BigDecimalWithNumericArgument:
  Enabled: true
  
Performance/RedundantSortBlock:
  Enabled: true
  
Performance/RedundantStringChars:
  Enabled: true
  
Performance/ReverseFirst:
  Enabled: true
  
Performance/SortReverse:
  Enabled: true
  
Performance/Squeeze:
  Enabled: true
  
Performance/StringInclude:
  Enabled: true
  


RSpec/ExampleWording:
  Enabled: false

RSpec/InstanceVariable:
  AssignmentOnly: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/PredicateMatcher:
  Exclude:
    - 'spec/basic_node_spec.rb'

Capybara/FeatureMethods:
  Enabled: false
